add: checks in scripts

diff --git a/common/non-ascii b/common/non-ascii
--- a/common/non-ascii
+++ b/common/non-ascii
@@ -1,3 +1,13 @@
 #!/usr/bin/env bash
 
-cat "${1}" | awk '{printf("L%d : %s \n", NR, $0)}' | perl -ne 'print if /[^[:ascii:]]/'
+if [ "$#" -ne 1 ]; then
+    echo "Usage: $(basename "$0") <file>"
+    exit 1
+fi
+
+if [ ! -f "$1" ]; then
+    echo "Could not find $1"
+    exit 1
+fi
+
+cat "$1" | awk '{printf("L%d : %s \n", NR, $0)}' | perl -ne 'print if /[^[:ascii:]]/'
